---
title: "Data Visualisation"
toc: true
toc-location: right
---

# Introduction

This module introduces you to data visualisation in R. 

## Module Learning Objectives

The Module Learning outcomes are:

- Explore and understand datasets by visualising distributions, relationships, and trends.

- Design clear and comprehensible visualisations that avoid common pitfalls.

- Communicate findings to diverse audiences through compelling storytelling.

- Build interactive dashboards that combine multiple visualisations.

- Apply these skills across your degree and in a wide range of careers.

# How Data Visualisation is organized

Data visualisation is organized so that each week, you are introduced to a topic and get hands-on practice. To help your learning go smoothly, the organization is designed to be similar to the data analysis module that students will be completing at the same time.

Each week has:

-   An overview on the "About" page which gives the Learning Objectives, a topic summary and the instructions for the week. You should read this first.

-   Some independent study on the "Prepare!" page to prepare you for the seminar and practical. This will be reading from the [course book](https://clauswilke.com/dataviz/), completing lessons on DataCamp, or doing some coding or set up.

- A one-hour seminar in which I will walk you through the topic for the week.

-   A two-hour practical using R. You will spend most of the session going through some exercises. Anything you have not done before is explained and guided but you will also have to use the skills gained in previous practicals.

-   Some independent study on the "Consolidate!" page to give you more practice. The exercises are usually similar to those in the practical but with less guidance.

# Content

## Week 1: Principles of Data Visualisation

This week you will read a short paper about what makes a good visualization, and we will discuss this topic further in the seminar. There will be no practical.

## Week 2: Grammar of Graphics

This week you will be introduced to the fundamental tool for building visualizations in R: the grammar of graphics. We will discuss elements of the grammar of graphics in the seminar, and you will practice using it in the practical. In preparation for this week, you will start working through lessons on DataCamp on wrangling data in R using the **tidyverse**.

## Week 3: Distributions

This week, we will dive into how to plot the shape and range of variables in data. We will discuss common plots including histograms, density plots, boxplots and violin plots, and you will gain practice creating these graphs in the practical. You will also continue working through **tidyverse** lessons on DataCamp.


## Week 4: Bar Plots for Categorical Data

This week, we will explore bar plots as a key tool for plotting characteristics of categorical data. We will discuss how to use bar plots to depict counts, proportions and summary statistics, and you will gain practice using bar plots in the practical.

## Week 5: Relationships between Variables

This week, we will examine relationships between variables. We will do a deep dive into scatterplots, adding trend lines, depicting how relationships differ across categorical groups, and correlation matrices. The practical will walk you through building these plots. To prepare for the following week, you will complete lessons on working with date and time variables on DataCamp.

## Week 6: Time Series and Line Graphs

This week, we will explore how to visualise changes over time using line graphs. We will discuss how to de-clutter and emphasize temporal trends and work with date and time variables in the seminar, and you will practice depicting temporal data in the practical.

# Resources

## Tidyverse 

Data wrangling [cheat sheet](https://stat33b.berkeley.edu/spring-2025/cheatsheets/dplyr-cheatsheet.pdf)

Data wrangling [in depth](https://r4ds.had.co.nz/wrangle-intro.html)

DataCamp courses

## Data Visualisation

[Fundamentals of Data Visualization](https://clauswilke.com/dataviz/index.html)

Explore [graph types](https://www.data-to-viz.com/#explore)





